/**
 * TypeScript types for DICOM metadata JSON generated by the Python converter
 */

/**
 * Metadata for a DICOM series converted to float16 raw buffers
 */
export interface DicomSeriesMetadata {
  // Volume dimensions
  /** Number of slices in the volume */
  numSlices: number;
  
  /** Width of each slice in pixels */
  width: number;
  
  /** Height of each slice in pixels */
  height: number;
  
  /** Data format (always "float16") */
  format: "float16";
  
  /** Bytes per voxel (always 2 for float16) */
  bytesPerVoxel: 2;
  
  // Patient information
  /** Patient's full name */
  patientName: string;
  
  /** Patient identifier */
  patientID: string;
  
  /** Patient's birth date (YYYYMMDD format) */
  patientBirthDate: string;
  
  /** Patient's sex (M/F/O) */
  patientSex: string;
  
  // Study information
  /** Date the study was performed (YYYYMMDD format) */
  studyDate: string;
  
  /** Time the study was performed (HHMMSS format) */
  studyTime: string;
  
  /** Description of the study */
  studyDescription: string;
  
  /** Unique identifier for the study */
  studyInstanceUID: string;
  
  // Series information
  /** Series number within the study */
  seriesNumber: string;
  
  /** Description of the series */
  seriesDescription: string;
  
  /** Unique identifier for the series */
  seriesInstanceUID: string;
  
  /** Imaging modality (CT, MR, etc.) */
  modality: string;
  
  // Spatial information
  /** Physical distance between pixel centers [row spacing, column spacing] in mm */
  pixelSpacing: string | number[];
  
  /** Thickness of each slice in mm */
  sliceThickness: string;
  
  /** Direction cosines of the first row and column of the image [6 values] */
  imageOrientationPatient: string | number[];
  
  /** Position of the first voxel [x, y, z] in mm */
  imagePositionPatient: string | number[];
  
  // Display parameters
  /** Window center for display (can be single value or array) */
  windowCenter: string | number | number[];
  
  /** Window width for display (can be single value or array) */
  windowWidth: string | number | number[];
  
  // Rescale parameters (from original DICOM)
  /** Slope for rescaling pixel values */
  rescaleSlope: string;
  
  /** Intercept for rescaling pixel values */
  rescaleIntercept: string;

  huMin: string|number;
  huMax: string|number;

  chunkSize : string|number;
  numChunksX : string|number;
  numChunksY : string|number;
  numChunksZ : string|number;
  totalChunks : string|number;
}

/**
 * Parsed version of DicomSeriesMetadata with typed numeric arrays
 */
export interface ParsedDicomMetadata {
  // Volume dimensions
  numSlices: number;
  width: number;
  height: number;
  format: "float16";
  bytesPerVoxel: 2;
  
  // Patient information
  patientName: string;
  patientID: string;
  patientBirthDate: string;
  patientSex: string;
  
  // Study information
  studyDate: string;
  studyTime: string;
  studyDescription: string;
  studyInstanceUID: string;
  
  // Series information
  seriesNumber: number;
  seriesDescription: string;
  seriesInstanceUID: string;
  modality: string;
  
  // Spatial information (parsed as numbers)
  pixelSpacing: [number, number];
  sliceThickness: number;
  imageOrientationPatient: number[];
  imagePositionPatient: [number, number, number];
  
  // Display parameters
  windowCenter: number | number[];
  windowWidth: number | number[];
  
  // Rescale parameters
  rescaleSlope: number;
  rescaleIntercept: number;

  huMin: number;
  huMax: number;

  chunkSize: number;
  numChunksX: number;
  numChunksY: number;
  numChunksZ: number;
  totalChunks: number;
}

/**
 * Helper function to parse raw metadata into typed version
 */
export function parseMetadata(raw: DicomSeriesMetadata): ParsedDicomMetadata {
  // Helper to parse array-like strings
  const parseArray = (val: string | number[]): number[] => {
    if (Array.isArray(val)) return val;
    if (typeof val === 'string') {
      try {
        const parsed = JSON.parse(val);
        return Array.isArray(parsed) ? parsed : [parseFloat(val)];
      } catch {
        return [parseFloat(val)];
      }
    }
    return [];
  };
  
  // Helper to parse single value
  const parseNumber = (val: string | number): number => {
    if (typeof val === 'number') return val;
    if (Array.isArray(val)) return parseFloat(val[0]);
    return parseFloat(val) || 0;
  };
  
  const pixelSpacingArray = parseArray(raw.pixelSpacing);
  const imagePositionArray = parseArray(raw.imagePositionPatient);
  
  return {
    numSlices: raw.numSlices,
    width: raw.width,
    height: raw.height,
    format: raw.format,
    bytesPerVoxel: raw.bytesPerVoxel,
    
    patientName: raw.patientName,
    patientID: raw.patientID,
    patientBirthDate: raw.patientBirthDate,
    patientSex: raw.patientSex,
    
    studyDate: raw.studyDate,
    studyTime: raw.studyTime,
    studyDescription: raw.studyDescription,
    studyInstanceUID: raw.studyInstanceUID,
    
    seriesNumber: parseNumber(raw.seriesNumber),
    seriesDescription: raw.seriesDescription,
    seriesInstanceUID: raw.seriesInstanceUID,
    modality: raw.modality,
    
    pixelSpacing: [
      pixelSpacingArray[0] || 1,
      pixelSpacingArray[1] || 1
    ],
    sliceThickness: parseNumber(raw.sliceThickness),
    imageOrientationPatient: parseArray(raw.imageOrientationPatient),
    imagePositionPatient: [
      imagePositionArray[0] || 0,
      imagePositionArray[1] || 0,
      imagePositionArray[2] || 0
    ],
    
    windowCenter: typeof raw.windowCenter === 'string' 
      ? parseNumber(raw.windowCenter)
      : raw.windowCenter,
    windowWidth: typeof raw.windowWidth === 'string'
      ? parseNumber(raw.windowWidth)
      : raw.windowWidth,
    
    rescaleSlope: parseNumber(raw.rescaleSlope),
    rescaleIntercept: parseNumber(raw.rescaleIntercept),

    huMin: parseNumber(raw.huMin),
    huMax: parseNumber(raw.huMax),

    chunkSize: parseNumber(raw.chunkSize),
    numChunksX: parseNumber(raw.numChunksX),
    numChunksY: parseNumber(raw.numChunksY),
    numChunksZ: parseNumber(raw.numChunksZ),
    totalChunks: parseNumber(raw.totalChunks)
  };
}

/**
 * Example usage:
 * 
 * ```typescript
 * // Load metadata
 * const response = await fetch('./output/metadata.json');
 * const metadata: DicomSeriesMetadata = await response.json();
 * 
 * // Parse for easier use
 * const parsed = parseMetadata(metadata);
 * 
 * console.log(`Volume: ${parsed.width}x${parsed.height}x${parsed.numSlices}`);
 * console.log(`Pixel spacing: ${parsed.pixelSpacing[0]}mm x ${parsed.pixelSpacing[1]}mm`);
 * console.log(`Slice thickness: ${parsed.sliceThickness}mm`);
 * ```
 */